### ISSUE TITLE
If you're in there

### ISSUE THREAD

**Issue by yeesian** [meggart/OGR_Wrapper#1]
can you help with the header files for the spatial reference system: http://www.gdal.org/ogr__srs__api_8h_source.html? It'll help a great deal for eventual integration with Proj4.jl later.

**Comment by yeesian** [comment]
@visr

**Comment by visr** [comment]
https://github.com/visr/GDAL.jl/commit/1bd4633c19bcb85ab36e8cdf974e4b25cca65f52

**Comment by yeesian** [comment]
:+1:
